version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - database-data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  database-data:
